@BASE = http://localhost:8080
@ACCESS = paste_access_token_here
@REFRESH = paste_refresh_token_here

### Health Check
GET {{BASE}}/health

### Sign Up
POST {{BASE}}/api/auth/signup
Content-Type: application/json

{
  "loginId": "yeeunee",
  "password": "123456789!",
  "name": "김예은",
  "gender": "F",
  "phone": "010-3370-7588",
  "birthDate": "2004-02-12",
  "smsConsent": true,
  "termsConsent": true
}

### Login
POST {{BASE}}/api/auth/login
Content-Type: application/json

{
  "loginId": "yeeunee",
  "password": "123456789!"
}

### Get Profile
GET {{BASE}}/api/me
Authorization: Bearer {{ACCESS}}

### Refresh Tokens
POST {{BASE}}/api/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{REFRESH}}"
}

### Logout
POST {{BASE}}/api/auth/logout
Content-Type: application/json

{
  "refreshToken": "{{REFRESH}}"
}
