@base = http://localhost:4000

### signup
POST {{base}}/api/auth/signup
Content-Type: application/json

{
  "email": "saim@example.com",
  "password": "Passw0rd!",
  "nickname": "saim"
}

### login
# @name login
POST {{base}}/api/auth/login
Content-Type: application/json

{
  "email": "saim@example.com",
  "password": "Passw0rd!"
}

### me
GET {{base}}/api/me
Authorization: Bearer {{login.response.body.token}}
